config/routes.rb
StorenvyOauthClient::Application.routes.draw do
  
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"} do
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  match 'explore/*api' => 'api#explore', :as => :explore_api
  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutabl
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # devise :omniauthable
  
  def self.find_or_initialize_for_storenvy_oauth(oauth_data)    
    User.find_or_initialize_by_storenvy_uid(oauth_data.uid).tap do |user|
      user.email    = oauth_data.info.email
      user.login    = oauth_data.info.login
      user.bio      = oauth_data.info.bio
      user.location = oauth_data.info.location
      user.gender   = oauth_data.info.gender
      user.twitter  = oauth_data.info.twitter
      user.facebook = oauth_data.info.facebook
      user.birthday = oauth_data.info.birthday
      user.password = Devise.friendly_token[0,20] if user.new_record?
    end
  end

  def update_storenvy_credentials(oauth_data)
    self.storenvy_access_token = oauth_data.credentials.token
  end
  
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  respond_to :json

  def explore
    begin
      if storenvy_access_token.nil?
        @json                  = { message: "Your session has expired. Please log out and back into this client app." }
        session[:user_id]      = nil
        session[:access_token] = nil
      end
      @json = storenvy_access_token.get("/v1/#{params[:api]}.json#{aggregate_params}").parsed
    rescue => e
      @json = { message: "An Oauth excecption occurred. You may have requested something you don't have access to." }
    end
    respond_with @json
  end

  # HACK
  def aggregate_params
    param_str = '?'
    request.query_parameters.each do |param|
      param_str += "#{param.first}=#{param.second.gsub('.json','')}&"
    end
    param_str
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def storenvy_oauth_client
    Rails.logger.debug "\n\n #{STORENVY_OAUTH.inspect} \n\n"
    @client ||= OAuth2::Client.new(STORENVY_OAUTH[:app_id], STORENVY_OAUTH[:secret], :site => 'https://api.storenvy.com')
  end

  def storenvy_access_token
    @token ||= OAuth2::AccessToken.new(storenvy_oauth_client, current_user.storenvy_access_token) if current_user
  end
  
  private
  
  def oauth_client
    @oauth_client ||= OAuth2::Client.new(ENV["OAUTH_ID"], ENV["OAUTH_SECRET"], site: "http://localhost:3000")
  end

  def access_token
    if session[:access_token]
      @access_token ||= OAuth2::AccessToken.new(oauth_client, session[:access_token])
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def storenvy
    oauth_data = request.env["omniauth.auth"]
    @user = User.find_or_initialize_for_storenvy_oauth(oauth_data)
    @user.update_storenvy_credentials(oauth_data)
    @user.save!
    sign_in_and_redirect @user
  end

  def failure
  	Rails.logger.info request.env["omniauth.auth"].inspect
    Rails.logger.info request.env['omniauth.error'].inspect
    Rails.logger.info request.env['omniauth.error.type'].inspect
    Rails.logger.info request.env['omniauth.error.strategy'].inspect
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/callback.html.erb
<h1>Oauth Code</h1>
<code>
  <%= @code %>
</code>

app/views/home/index.html.haml
%section
  .row
    .span12
      - unless signed_in?
        %h3 Sign in first to explore the Storenvy API
        %br/
        %p
          %a.btn-storenvy{ href: user_omniauth_authorize_path(:storenvy) }
            %i
            Sign in with Storenvy
      - else
        %h2 Explore the Storenvy API
        .well
          = link_to "My User", explore_api_path(:me, format: :json), class:  "btn explore-api", "data-type" => 'text', remote: true
          = link_to "Store", explore_api_path(:store, format: :json), class:  "btn explore-api", "data-type" => 'text', remote: true
          = link_to "Products", explore_api_path(:products, format: :json), class:  "btn explore-api", "data-type" => 'text', remote: true
          = link_to "Collections", explore_api_path(:collections, format: :json), class:  "btn explore-api", "data-type" => 'text', remote: true
          = link_to "Orders", explore_api_path(:orders, format: :json), class:  "btn explore-api", "data-type" => 'text', remote: true
          = link_to "Shipping Groups", explore_api_path(:shipping_groups, format: :json), class:  "btn explore-api","data-type" => 'text', remote: true
          = link_to "Shipping Classes", explore_api_path(:shipping_classes, format: :json), class:  "btn explore-api", "data-type" => 'text', remote: true
          = link_to "Webhooks", explore_api_path(:webhooks, format: :json), class:  "btn explore-api", "data-type" => 'text', remote: true
          = form_tag "#", id: "api-explorer", style: "margin-top:20px" do
            %label{for: "explore-url",style: "font-weight:bold"}
              Endpoint
            %span{style: "white-space:no-wrap"}
              http://api.storenvy.com/v1/
              = text_field :url, nil, id: "explore-url"
              \.json
            = submit_tag "Send request"
        #api-response
        #spinner-wrapper
          .spinner
            .bar1
            .bar2
            .bar3
            .bar4
            .bar5
            .bar6
            .bar7
            .bar8
            .bar9
            .bar10
            .bar11
            .bar12

app/views/layouts/application.html.haml
!!! 5
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}
    %title Storenvy Oauth Client Starter
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %meta{name: "description", content:"Your app's description."}
    %meta{name: "author", content:"Your name."}
 
    / Le HTML5 shim, for IE6-8 support of HTML elements
    / [if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    
    / Le styles
    = stylesheet_link_tag "/css/bootstrap.css"
    
    :css
      body {
           padding-top: 60px; 
           /* 60px to make the container go all the way to the bottom of the topbar */
         }
    = stylesheet_link_tag "/css/bootstrap-responsive.css"
    = stylesheet_link_tag "application"
    = csrf_meta_tags
    = javascript_include_tag :application  
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          = link_to "Storenvy Oauth Rails Client", root_path, class: "brand"
          .btn-group.pull-right
            - if user_signed_in?
              = link_to "#", class: "btn-primary dropdown-toggle", data: {toggle: "dropdown"} do
                %span.link-wrapper
                  = current_user.login
                %span.caret
              %ul.dropdown-menu              
                %li= link_to "Sign out", destroy_user_session_path, method: :delete
            - else
              %a.btn-storenvy.on-dark{ href: user_omniauth_authorize_path(:storenvy) }
                %i
                Sign in with Storenvy

    .container
      = yield

    %script{src: "/js/bootstrap.js"}

    / For syntax highlighting. Remove if you build something else.
    =stylesheet_link_tag "/css/sunburst.css"
    %script{src: "/js/prettify.js"}